/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pembayaran.tampil;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;
import javax.swing.Timer;

public class MenuUtama extends javax.swing.JFrame {
    
    private DataKelas kls;
    private DataAngkatan angkatan;
    private DataJenis add;
//    private Daftar Ddaftar;
    private DataSiswa D_siswa;
    private Jenis Jjenis;
    private ProsesPembayaran P_pembayaran;
    private ProsesPembayaranSPP spp;
    //private ProsesPembayaranSPP P_SPP;
    private LaporanDataSiswa Lap_siswa;
    private LaporanJenis Lap_jenis;
    private LaporanPembayaran Lap_pembayaran;
    private LaporanProsesPembayaranSPP Lap_SPP;
    private CetakLaporanParameter cetak;
    
    
   private void setJam () {
        ActionListener listener = new ActionListener () {
            @Override
            public void actionPerformed (ActionEvent evt) {
                jam.setText (new WaktuSekarang().getWkt());
            }
        };
        new Timer (1000, listener). start();
    }
    
    private void ResetPusat() {
        try {
            DesktopPane.getSelectedFrame().setClosed (true);
        }catch (Exception e) {}
    }
    private void PusatBar (javax.swing.plaf.InternalFrameUI jif_f) {
        ((javax.swing.plaf.basic.BasicInternalFrameUI)jif_f).setNorthPane(null);
    }
    
    public MenuUtama() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
        setJam();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        DesktopPane = new DesktopPaneBackground();
        jLabel1 = new javax.swing.JLabel();
        jam = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tgl = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem14 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();

        setMaximumSize(new java.awt.Dimension(1364, 729));
        setMinimumSize(new java.awt.Dimension(1364, 729));
        setPreferredSize(new java.awt.Dimension(1364, 729));

        jPanel1.setBackground(new java.awt.Color(0, 232, 176));

        DesktopPane.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout DesktopPaneLayout = new javax.swing.GroupLayout(DesktopPane);
        DesktopPane.setLayout(DesktopPaneLayout);
        DesktopPaneLayout.setHorizontalGroup(
            DesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        DesktopPaneLayout.setVerticalGroup(
            DesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );

        jLabel1.setFont(new java.awt.Font("Lucida Sans", 1, 18)); // NOI18N
        jLabel1.setText("PUKUL : ");

        jam.setFont(new java.awt.Font("Lucida Sans", 1, 18)); // NOI18N
        jam.setText(new WaktuSekarang().getWkt());

        jLabel3.setFont(new java.awt.Font("Lucida Sans", 1, 18)); // NOI18N
        jLabel3.setText("TANGGAL : ");

        tgl.setFont(new java.awt.Font("Lucida Sans", 1, 18)); // NOI18N
        tgl.setText(new WaktuSekarang().getTgl());

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jam)
                .addGap(30, 30, 30)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tgl)
                .addContainerGap(704, Short.MAX_VALUE))
            .addComponent(DesktopPane)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jam)
                    .addComponent(jLabel3)
                    .addComponent(tgl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(DesktopPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jMenuBar1.setBorder(null);

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pembayaran/gambar/Icon/1 - user.png"))); // NOI18N
        jMenu1.setText("User");

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pembayaran/gambar/must_have_icon_set/Log Out/Log Out_16x16.png"))); // NOI18N
        jMenuItem1.setText("Logout");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pembayaran/gambar/Icon/key.png"))); // NOI18N
        jMenuItem4.setText("Daftar");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuBar1.add(jMenu1);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pembayaran/gambar/Icon/2 - master small.png"))); // NOI18N
        jMenu2.setText("Master Data");

        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pembayaran/gambar/Icon/2 - master small.png"))); // NOI18N
        jMenuItem2.setText("Data Siswa");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pembayaran/gambar/Icon/2 - master small.png"))); // NOI18N
        jMenuItem3.setText("Jenis");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuItem5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pembayaran/gambar/Icon/2 - master small.png"))); // NOI18N
        jMenuItem5.setText("Edit Data Jenis");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem5);

        jMenuItem13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pembayaran/gambar/Icon/2 - master small.png"))); // NOI18N
        jMenuItem13.setText("Edit Data Kelas");
        jMenuItem13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem13ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem13);

        jMenuItem11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pembayaran/gambar/Icon/2 - master small.png"))); // NOI18N
        jMenuItem11.setText("Edit Data Angkatan");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem11);

        jMenuBar1.add(jMenu2);

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pembayaran/gambar/Icon/3 - mahasiswa small.png"))); // NOI18N
        jMenu3.setText("Proses");

        jMenuItem6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pembayaran/gambar/Icon/3 - mahasiswa small.png"))); // NOI18N
        jMenuItem6.setText("Proses Pembayaran");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem6);

        jMenuItem14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pembayaran/gambar/Icon/3 - mahasiswa small.png"))); // NOI18N
        jMenuItem14.setText("Proses Pembayaran SPP");
        jMenuItem14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem14ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem14);

        jMenuBar1.add(jMenu3);

        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pembayaran/gambar/Icon/Admin-Schoolar-Icon.png"))); // NOI18N
        jMenu4.setText("Cetak Laporan");

        jMenuItem7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pembayaran/gambar/Icon/Admin-Schoolar-Icon.png"))); // NOI18N
        jMenuItem7.setText("Cetak Data Siswa");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem7);

        jMenuItem9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pembayaran/gambar/Icon/Admin-Schoolar-Icon.png"))); // NOI18N
        jMenuItem9.setText("Cetak Jenis");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem9);

        jMenuItem10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pembayaran/gambar/Icon/Admin-Schoolar-Icon.png"))); // NOI18N
        jMenuItem10.setText("Cetak Pembayaran Semua");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem10);

        jMenuItem12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pembayaran/gambar/Icon/Admin-Schoolar-Icon.png"))); // NOI18N
        jMenuItem12.setText("Cetak Pembayaran SPP Semua");
        jMenuItem12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem12ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem12);

        jMenuItem8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pembayaran/gambar/Icon/Admin-Schoolar-Icon.png"))); // NOI18N
        jMenuItem8.setText("Cetak Berdasarkan Tanggal ");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem8);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        try {
            ResetPusat();
            if (D_siswa==null || D_siswa.isClosed()==true) {
                D_siswa = new DataSiswa();
                DesktopPane.add(D_siswa);
            }else {
                D_siswa.toFront();
            }
            D_siswa.setVisible(true);
            D_siswa.setSelected(true);
            D_siswa.setSize(DesktopPane.getSize());
            PusatBar(D_siswa.getUI());
        }catch(Exception e) {
            JOptionPane.showMessageDialog(null, "Gagal Menampilkan Halaman Data Siswa");
        }
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        try {
            ResetPusat();
            if (Jjenis==null || Jjenis.isClosed()==true) {
                Jjenis = new Jenis();
                DesktopPane.add(Jjenis);
            }else {
                Jjenis.toFront();
            }
            Jjenis.setVisible(true);
            Jjenis.setSelected(true);
            Jjenis.setSize(DesktopPane.getSize());
            PusatBar(Jjenis.getUI());
        }catch(Exception e) {
            JOptionPane.showMessageDialog(null, "Gagal Menampilkan Halaman Jenis");
        }
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
        try {
            ResetPusat();
            if (P_pembayaran==null || P_pembayaran.isClosed()==true) {
                P_pembayaran = new ProsesPembayaran();
                DesktopPane.add(P_pembayaran);
            }else {
                P_pembayaran.toFront();
            }
            P_pembayaran.setVisible(true);
            P_pembayaran.setSelected(true);
            P_pembayaran.setSize(DesktopPane.getSize());
            PusatBar(P_pembayaran.getUI());
        }catch(Exception e) {
            JOptionPane.showMessageDialog(null, "Gagal Menampilkan Halaman Proses Pembayaran");
        }
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // TODO add your handling code here:
        try {
            ResetPusat();
            if (Lap_siswa==null || Lap_siswa.isClosed()==true) {
                Lap_siswa = new LaporanDataSiswa();
                DesktopPane.add(Lap_siswa);
            }else {
                Lap_siswa.toFront();
            }
            Lap_siswa.setVisible(true);
            Lap_siswa.setSelected(true);
            Lap_siswa.setSize(DesktopPane.getSize());
            PusatBar(Lap_siswa.getUI());
        }catch(Exception e) {
            JOptionPane.showMessageDialog(null, "Gagal Menampilkan Halaman Laporan Data Siswa");
        }
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        // TODO add your handling code here:
        try {
            ResetPusat();
            if (Lap_jenis==null || Lap_jenis.isClosed()==true) {
                Lap_jenis = new LaporanJenis();
                DesktopPane.add(Lap_jenis);
            }else {
                Lap_jenis.toFront();
            }
            Lap_jenis.setVisible(true);
            Lap_jenis.setSelected(true);
            Lap_jenis.setSize(DesktopPane.getSize());
            PusatBar(Lap_jenis.getUI());
        }catch(Exception e) {
            JOptionPane.showMessageDialog(null, "Gagal Menampilkan Halaman laporan Jenis");
        }
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        // TODO add your handling code here:
        try {
            ResetPusat();
            if (Lap_pembayaran==null || Lap_pembayaran.isClosed()==true) {
                Lap_pembayaran = new LaporanPembayaran();
                DesktopPane.add(Lap_pembayaran);
            }else {
                Lap_pembayaran.toFront();
            }
            Lap_pembayaran.setVisible(true);
            Lap_pembayaran.setSelected(true);
            Lap_pembayaran.setSize(DesktopPane.getSize());
            PusatBar(Lap_pembayaran.getUI());
        }catch(Exception e) {
            JOptionPane.showMessageDialog(null, "Gagal Menampilkan Halaman Laporan Pembayaran");
        }
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        int confirm = JOptionPane.showConfirmDialog(this, "Konfirmasi Keluar Aplikasi", "Yakin keluar dari Program",JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (confirm == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        new Daftar().setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem12ActionPerformed
        // TODO add your handling code here:
        try {
            ResetPusat();
            if (Lap_SPP==null || Lap_SPP.isClosed()==true) {
                Lap_SPP = new LaporanProsesPembayaranSPP();
                DesktopPane.add(Lap_SPP);
            }else {
                Lap_SPP.toFront();
            }
            Lap_SPP.setVisible(true);
            Lap_SPP.setSelected(true);
            Lap_SPP.setSize(DesktopPane.getSize());
            PusatBar(Lap_SPP.getUI());
        }catch(Exception e) {
            JOptionPane.showMessageDialog(null, "Gagal Menampilkan Halaman Daftar");
        }
    }//GEN-LAST:event_jMenuItem12ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        try {
            ResetPusat();
            if (add==null || add.isClosed()==true) {
                add = new DataJenis();
                DesktopPane.add(add);
            }else {
                add.toFront();
            }
            add.setVisible(true);
            add.setSelected(true);
            add.setSize(DesktopPane.getSize());
            PusatBar(add.getUI());
        }catch(Exception e) {
            JOptionPane.showMessageDialog(null, "Gagal Menampilkan Halaman Daftar");
        }
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        // TODO add your handling code here:
         try {
            ResetPusat();
            if (angkatan==null || angkatan.isClosed()==true) {
                angkatan = new DataAngkatan();
                DesktopPane.add(angkatan);
            }else {
                angkatan.toFront();
            }
            angkatan.setVisible(true);
            angkatan.setSelected(true);
            angkatan.setSize(DesktopPane.getSize());
            PusatBar(angkatan.getUI());
        }catch(Exception e) {
            JOptionPane.showMessageDialog(null, "Gagal Menampilkan Halaman Daftar");
        }
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void jMenuItem13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem13ActionPerformed
        // TODO add your handling code here:
         try {
            ResetPusat();
            if (kls==null || kls.isClosed()==true) {
                kls = new DataKelas();
                DesktopPane.add(kls);
            }else {
                kls.toFront();
            }
            kls.setVisible(true);
            kls.setSelected(true);
            kls.setSize(DesktopPane.getSize());
            PusatBar(kls.getUI());
        }catch(Exception e) {
            JOptionPane.showMessageDialog(null, "Gagal Menampilkan Halaman Daftar");
        }
    }//GEN-LAST:event_jMenuItem13ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        // TODO add your handling code here:
      //  new CetakBerdasarkan(null,true).show();
       try {
            ResetPusat();
            if (cetak==null || cetak.isClosed()==true) {
                cetak = new CetakLaporanParameter();
                DesktopPane.add(cetak);
            }else {
                cetak.toFront();
            }
            cetak.setVisible(true);
            cetak.setSelected(true);
            cetak.setSize(DesktopPane.getSize());
            PusatBar(cetak.getUI());
        }catch(Exception e) {
            JOptionPane.showMessageDialog(null, "Gagal Menampilkan Halaman Daftar");
        }
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem14ActionPerformed
        // TODO add your handling code here:
        try {
            ResetPusat();
            if (spp==null || spp.isClosed()==true) {
                spp = new ProsesPembayaranSPP();
                DesktopPane.add(spp);
            }else {
                spp.toFront();
            }
            spp.setVisible(true);
            spp.setSelected(true);
            spp.setSize(DesktopPane.getSize());
            PusatBar(spp.getUI());
        }catch(Exception e) {
            JOptionPane.showMessageDialog(null, "Gagal Menampilkan Halaman Daftar");
        }
    }//GEN-LAST:event_jMenuItem14ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuUtama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane DesktopPane;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jam;
    private javax.swing.JLabel tgl;
    // End of variables declaration//GEN-END:variables
}
